# Check out depcheck at: https://github.com/depcheck/depcheck

ignores:
  - "@commitlint/*"
  - "@stryker-mutator/*"
  - "@types/*"
  - ts-jest
ignore-path: .gitignore

parsers:
  "**/*.cjs": es6
  "**/*.js": es6
  "**/*.ts": typescript
