name: Code Analysis
on:
  push:
    branches:
      - main
      - main-v2
  pull_request:
    branches:
      - main
      - main-v2
  schedule:
    - cron: '0 7 * * 3'

permissions: read-all

jobs:
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95 # renovate: tag=v1.4.5
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            ghcr.io:443
            github.com:443
            pkg-containers.githubusercontent.com:443
            uploads.github.com:443
      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - name: Initialize CodeQL
        uses: github/codeql-action/init@b398f525a5587552e573b247ac661067fafa920b # renovate: tag=v2.1.22
        with:
          config-file: ./.github/codeql-config.yml
          languages: javascript
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@b398f525a5587552e573b247ac661067fafa920b # renovate: tag=v2.1.22
