name: Config Validation
on:
  push:
    paths:
    - '.github/codecov.yml'
  pull_request:
    paths:
    - '.github/workflows/config-checks.yml'
    - '.github/codecov.yml'

permissions: read-all

jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95 # tag=v1.4.5
        with:
          egress-policy: block
          allowed-endpoints: >
            codecov.io:443
            github.com:443
      - name: Checkout Repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
      - name: Validate Codecov configuration
        run: sh script/validate-codecov-config.sh
