name: Dependency Analysis
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: read-all

jobs:
  npm-audit:
    name: Audit npm on ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - main
          - main-v2
          - v2
          - v3
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # tag=v1.5.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            ghcr.io:443
            github.com:443
            nodejs.org:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          ref: ${{ matrix.version }}
      - name: Install Node.js
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3.5.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Initialize repository
        run: npm ci
      - name: Audit npm dependencies
        run: npm run audit
