name: Dependency Analysis
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: read-all

jobs:
  npm-audit:
    name: Audit npm on ${{ matrix.version }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - main
          - main-v2
          - v2
          - v3
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@dd2c410b088af7c0dc8046f3ac9a8f4148492a95 # tag=v1.4.5
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            ghcr.io:443
            github.com:443
            nodejs.org:443
            registry.npmjs.org:443
            si05acprodeus1file1.blob.core.windows.net:443
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          ref: ${{ matrix.version }}
      - name: Install Node.js
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3.4.1
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Initialize repository
        run: npm ci
      - name: Audit npm dependencies
        run: npm run audit
