name: Nightly
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch: ~

permissions: read-all

jobs:
  audit:
    name: Audit
    uses: ericcornelissen/svgo-action/.github/workflows/reusable-audit.yml@main
    with:
      refs: >-
        [
          "main",
          "v3",
          "main-v2"
        ]
  tooling:
    name: Tool update ${{ matrix.tool }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write # To push a commit
      pull-requests: write # To open a Pull Request
    strategy:
      fail-fast: false
      matrix:
        tool:
          - act
          - actionlint
          - cosign
          - hadolint
          - shellcheck
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@c8454efe5d0bdefd25384362fe217428ca277d57 # v2.2.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            fulcio.sigstore.dev:443
            github.com:443
            gitlab.com:443
            objects.githubusercontent.com:443
            rekor.sigstore.dev:443
            sigstore-tuf-root.storage.googleapis.com:443
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Install tooling
        uses: asdf-vm/actions/install@707e84f3ee349548310aeabdad0dd3bfcb9b69fa # v1.1.0
      - name: Create automation token
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        id: automation-token
        with:
          app_id: ${{ secrets.AUTOMATION_APP_ID }}
          private_key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
      - name: Get latest version
        uses: nick-fields/retry@943e742917ac94714d2f408a0e8320f2d1fcafcd # v2.8.3
        with:
          max_attempts: 3
          retry_wait_seconds: 120
          timeout_seconds: 20
          command: >-
            LATEST_VERSION="$(asdf latest '${{ matrix.tool }}')"
            &&
            echo "latest=$LATEST_VERSION" >> "$GITHUB_ENV"
      - name: Install new version
        run: |
          asdf install '${{ matrix.tool }}' '${{ env.latest }}'
      - name: Apply latest version to .tool-versions
        run: |
          asdf local '${{ matrix.tool }}' '${{ env.latest }}'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          token: ${{ steps.automation-token.outputs.token }}
          title: Update ${{ matrix.tool }} to v${{ env.latest }}
          body: |
            _This Pull Request was created automatically_

            ---

            Bump ${{ matrix.tool }} to v${{ env.latest }}
          branch: tooling-${{ matrix.tool }}-${{ env.latest }}
          labels: dependencies
          commit-message: "chore: update ${{ matrix.tool }} to ${{ env.latest }}"
          add-paths: |
            .tool-versions
