name: Audit
on:
  workflow_call:
    inputs:
      refs:
        default: '[""]'
        required: false
        type: string

permissions: read-all

jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # tag=v1.5.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            ghcr.io:443
            github.com:443
            objects.githubusercontent.com:443
            pkg-containers.githubusercontent.com:443
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          fetch-depth: 0
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@5b07ceca8a89dc14d2191f4a202bd28fae3e76ad # tag=v2.2.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: false
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_ENABLE_SUMMARY: true
  npm:
    name: npm (${{ matrix.ref }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ref: ${{ fromJSON(inputs.refs) }}
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@2e205a28d0e1da00c5f53b161f4067b052c61f34 # tag=v1.5.0
        with:
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            artifactcache.actions.githubusercontent.com:443
            ghcr.io:443
            github.com:443
            nodejs.org:443
            objects.githubusercontent.com:443
            registry.npmjs.org:443
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          ref: ${{ matrix.ref }}
      - name: Install Node.js
        uses: actions/setup-node@969bd2663942d722d85b6a8626225850c2f7be4b # tag=v3.5.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install dependencies
        run: npm ci
      - name: Audit all npm dependencies
        if: ${{ !startsWith(matrix.ref, 'v') }}
        run: npm run audit
      - name: Audit production npm dependencies
        if: ${{ startsWith(matrix.ref, 'v') }}
        run: npm run audit -- --production
